name: 'Build'

on:
  push:
    branches: [main]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/setup_env
      - name: Build
        uses: ./.github/actions/build
